---
title: Kwago
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: isipkwago@gmail.com
description: Kwago  is a Manila-based, independent book distributor committed to building
  intimate spaces for readers and storytellers to connect, create and collaborate.
baseurl: ''
url: ''
instagram_username: isipkwago
facebook_username: isipkwago
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
